### PR TITLE
Batch network extraction on shift crafting fixes #2104

### LINKED ISSUE #2104: Bulk crafting blocks lags client
#### Issue description:
When bulk crafting blocks from ingot/gems, the game stutters and lags. Issue appears to exist in RS but not AE2. Has remarkable resemblance to #151.

#### What happens:
Game excessively lags when crafting blocks of material

#### What you expected to happen:
No stuttering, fast item movement to inventory

#### Steps to reproduce:
1. Fill storage with any number of ingots/gems, larger amounts cause greater lag (>10k)
2. Use crafting grid to make blocks of said ingots/gems, shift clicking to receive 64 stacks of blocks

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.10

Does this issue occur on a server?

Yes

[crafting.zip](https://github.com/raoulvdberge/refinedstorage/files/2612664/crafting.zip)

### PR DESCRIPTION
**Pull request by Darkere**
This issue is only present for external inventories with large amounts of slots. 

In a test with ~200 filled 64k disks the method took about 5ms. 

A small drawer system took it up to around 20ms per stack crafted. 

A colossal Chest with about 30k slots ended up with 10 seconds per stack crafted + server crash.

The same colossal chest with this fix is at around 130ms per stack crafted. 

Warning: This assumes that the ItemStorageCache is always synced. If it is possible for the ItemStorageCache to be desynced it may dupe items.

### CODE REVIEW

File: src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java [hunk 1]
```diff
@@ -53,7 +55,18 @@ public void onCrafted(INetworkAwareGrid grid, ICraftingRecipe recipe, PlayerEnti
...
             } else if (!slot.isEmpty()) { // We don't have a remainder, but the slot is not empty.
                 if (slot.getCount() == 1 && network != null) { // Attempt to refill the slot with the same item from the network, only if we have a network and only if it's the last item.
-                    ItemStack refill = network.extractItem(slot, 1, Action.PERFORM);
+                    ItemStack refill;
+                    if (networkCraftingItems == null) { // for regular crafting
+                        refill = network.extractItem(slot, 1, Action.PERFORM);
+                    } else { // for shift crafting
+                        if (networkCraftingItems.get(slot) != null) {
+                            refill = networkCraftingItems.remove(slot, 1).getStack().copy();
+                            refill.setCount(1);
```
Comment (raoulvdberge) [inline src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java:64]: Why call `setCount`?

File: src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java [hunk 2]
```diff
@@ -71,25 +84,54 @@ public void onCrafted(INetworkAwareGrid grid, ICraftingRecipe recipe, PlayerEnti
...
         ItemStack crafted = grid.getCraftingResult().getStackInSlot(0);
 
+        int amountCrafted = 0;
+        boolean useNetwork = network != null;
+
+        IStackList<ItemStack> networkCraftingItems = null;
+        if (useNetwork) {
+            // We need a modifiable list of the items in storage that are relevant for this craft.
+            networkCraftingItems = API.instance().createItemStackList();
+            for (int i = 0; i < matrix.getSizeInventory(); ++i) {
```
Comment (raoulvdberge) [inline src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java:99]: Why don't we use a copy of the network item stack list straight away? Instead of making this filtered list.

File: src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java [hunk 3]
```diff
@@ -71,25 +84,54 @@ public void onCrafted(INetworkAwareGrid grid, ICraftingRecipe recipe, PlayerEnti
...
+            grid.onCrafted(player, networkCraftingItems, extractedItems);
 
             craftedItemsList.add(crafted.copy());
 
             amountCrafted += crafted.getCount();
         } while (API.instance().getComparer().isEqual(crafted, grid.getCraftingResult().getStackInSlot(0)) && amountCrafted < crafted.getMaxStackSize());
 
-        INetwork network = grid.getNetwork();
+        if (useNetwork) {
+            extractedItems.getStacks().forEach(x -> network.extractItem(x.getStack(), x.getStack().getCount(), Action.PERFORM));
```
Comment (raoulvdberge) [inline src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java:124]: Rename `x` to `stack`

File: src/main/java/com/refinedmods/refinedstorage/container/slot/grid/ResultCraftingGridSlot.java [hunk 4]
```diff
@@ -23,7 +23,7 @@ public ItemStack onTake(PlayerEntity player, @Nonnull ItemStack stack) {
         onCrafting(stack);
 
         if (!player.getEntityWorld().isRemote) {
-            grid.onCrafted(player);
+            grid.onCrafted(player,null,null);
```
Comment (raoulvdberge) [inline src/main/java/com/refinedmods/refinedstorage/container/slot/grid/ResultCraftingGridSlot.java:26]: Formatting

File: src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java [hunk 5]
```diff
@@ -23,8 +24,9 @@
 import java.util.List;
 
 public class CraftingGridBehavior implements ICraftingGridBehavior {
+
     @Override
-    public void onCrafted(INetworkAwareGrid grid, ICraftingRecipe recipe, PlayerEntity player) {
+    public void onCrafted(INetworkAwareGrid grid, ICraftingRecipe recipe, PlayerEntity player, IStackList<ItemStack> networkCraftingItems, IStackList<ItemStack> extractedItems) {
```
Comment (raoulvdberge) [inline src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java:29]: I don't think this `networkCraftingItems` param is needed, we have a `INetworkAwareGrid`.

File: src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java [hunk 6]
```diff
@@ -23,8 +24,9 @@
 import java.util.List;
 
 public class CraftingGridBehavior implements ICraftingGridBehavior {
+
```
Comment (raoulvdberge) [inline src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java:27]: Mysterious newline

**Review by raoulvdberge — CHANGES_REQUESTED** [review]
Can you fix the merge conflicts?

File: src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java (hunk 1 above)
Comment (Darkere) [reply src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java:64]: good point. relic from previous iteration

File: src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java (hunk 2 above)
Comment (Darkere) [reply src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java:99]: This is faster. Copying all thousands of items with their NBT is not necessary here. We just need the up to 9 items that correspond to the items in the crafting grid. 

I'm later also calling `IStackList.remove()` which needs to iterate over the entire list.

File: src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java (hunk 5 above)
Comment (Darkere) [reply src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java:29]: The networkCraftingItems need to persist through each iteration. It caches the number of items that are in the system. Each iteration I remove some items from that list.

File: src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java (hunk 2 above)
Comment (raoulvdberge) [reply src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java:99]: Yeah, forgot NBT copying (and stack copying in general) is super slow. Can you extract this logic to another method, then? Makes the code more readable.

File: src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java [hunk 7]
```diff
@@ -71,28 +82,47 @@ public void onCrafted(INetworkAwareGrid grid, ICraftingRecipe recipe, PlayerEnti
...
         int maxCrafted = crafted.getMaxStackSize();
 
-        ForgeHooks.setCraftingPlayer(player);
+        int amountCrafted = 0;
+        boolean useNetwork = network != null;
+
+        IStackList<ItemStack> networkCraftingItems = null;
+        if (useNetwork) {
+            // We need a modifiable list of the items in storage that are relevant for this craft.
+            networkCraftingItems = createFilteredItemList(network,matrix);
```
Comment (raoulvdberge) [inline src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java:98]: Maybe add a comment stating that we create a filtered list for performance reasons.

File: src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java [hunk 8]
```diff
@@ -24,7 +25,7 @@
 
 public class CraftingGridBehavior implements ICraftingGridBehavior {
     @Override
-    public void onCrafted(INetworkAwareGrid grid, ICraftingRecipe recipe, PlayerEntity player) {
+    public void onCrafted(INetworkAwareGrid grid, ICraftingRecipe recipe, PlayerEntity player, IStackList<ItemStack> networkCraftingItems, IStackList<ItemStack> extractedItems) {
```
Comment (raoulvdberge) [inline src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java:28]: We should probably mark these 2 params with `@Nullable`

Comment (raoulvdberge) [reply src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java:28]: Renaming `networkCraftingItems` to `availableItems` is probably better.

File: src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java (hunk 7 above)
Comment (raoulvdberge) [reply src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java:98]: Formatting `network,matrix`

File: src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java (hunk 8 above)
Comment (raoulvdberge) [reply src/main/java/com/refinedmods/refinedstorage/apiimpl/network/grid/CraftingGridBehavior.java:28]: `extractedItems` is slightly confusing since we didn't actually extract. `usedItems` perhaps?

**Review by raoulvdberge — CHANGES_REQUESTED** [review]

**Comment by raoulvdberge** [comment]
Lovely, thank you
